eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://127.0.0.1:9411/  # zipkin服务器的地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web  # 设置使用http的方式传输数据
    sleuth:
      sampler:
        probability: 1  # 设置抽样采集率为100%，默认为0.1，即10%

feign:
  hystrix:
    enabled: true
