eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  cloud:
    config:
      label: master
      profile: dev
      uri:
        - http://localhost:8888/
feign:
  hystrix:
    enabled: true
