eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: service-ribbon
    feign:
      path: /feign/**
      serviceId: service-feign
    hi:
      path: /base/**
      serviceId: service-hi
